### ISSUE TITLE
Lightning Design System CSS using old version (2.13.1 vs at least 2.21.1)

### ISSUE THREAD

**Issue by anderg4** [divriots/lwc.studio#5]
Lightning Design System CSS seems to be quite old (2.13.1 vs current which I think is Lightning Design System 2.21.1).  Things like comboboxes are not supported on lwc.studio – and rendering is not quite right when a component is transferred back to Salesforce.

**Comment by georges-gomes** [comment]
Hi! Thanks for reporting this.

I looked at your demo of the combo.

I upgraded the component library on LWC.studio
You can do it by editing the `lwc.config.json` file:
<img width="822" alt="image" src="https://github.com/divriots/lwc.studio/assets/5250572/0a1f7bfa-b035-4df2-b76a-42e4864e4de9">

https://app.lwc.studio/edit/sCr78mjyfFLsA2DiXmYS/lwc.config.json?p=stories

to version `1.18.8-alpha`.

But in both cases I don't see any difference with the official combobox.
https://developer.salesforce.com/docs/component-library/bundle/lightning-combobox/example

Let me know if it affects your styled combobox the way you want.

---

If it's not fixing your issue, I guess you are styling the combobox in your main projet. Let me know if this upgrade gives you the same result.
If you have some screenshot of the resulting problem (in LWC and in Salesforce) that would also help.

Thanks

**Comment by georges-gomes** [comment]
I updated the default template with SLDS `2.21.2-fix` (latest) (in `index.stories.js`) and the base components to `1.18.8-alpha`.

You should be good now but I think you already figured some of this by yourself as your demo was updated with `2.21.1` already 👍 

Now you just need to start a new project and the latest SLDS will be used.

**Comment by georges-gomes** [comment]
Please reopen if needed.
